numeric_settings:
  slurm_job_name: "turb_athenapk_gpu"
  number_of_gpus: 1  # max. 4 in Kultrun
  number_of_nodes: 1  # per GPU
  number_of_tasks: 1  # per node
  number_of_cells: 256
  max_memory: "40G"

initial_conditions:
  equation_of_state_type: "adiabatic"
  equation_of_state_gamma: 1.0001  # default: 1.0001 (~isothermal)
  initial_mean_density: 1.0  # default: 1.0
  initial_mean_pressure: 1.0  # default: 1.0
  initial_magnetic_field: 5.0  # default: 0.05 (x-direction)
  magnetic_field_mode: 4  # 0: net flux; 1: no net flux uniform B; 2: non net flux sin B; 4: field loop
  acceleration_field_rms: 1.0  # default: 1.0
  solenoidal_weight: 1.0  # 0: fully compressive; 1: fully solenoidal
  correlation_time: 1.0  # default: 1.0

post_analysis:
  run_analysis: 0  # 0: no analysis; 1: simple; 2: flow; 3: energy transfer
  weight: None
  fields_for_analysis:
    - "density"
    - "mach_number"
    - "sound_speed"
    - "magnetic_energy_density"
    - "magnetic_field_magnitude"
