# Numeric settings
slurm_job_name: "turb_athenapk_gpu"
number_of_gpus: 1  # max. 4 in Kultrun
number_of_nodes: 1  # per GPU
number_of_tasks: 1  # per node
max_memory: "40G"
number_of_cells: 128

# Initial conditions
equation_of_state: "adiabatic"
initial_density: 1.0
initial_magnetic_field: 0.05  # default: 0.05 (x-direction)
acceleration_field_rms: 0.1
correlation_time: 1.0
solenoidal_weight: 1.0  # 0: fully compressive; 1: fully solenoidal

# Post-run analysis
run_analysis: True
fields_for_analysis:
  - "mach_number"
