# Numeric settings
number_of_gpus: 1  # max. 4 in Kultrun
number_of_cells: 256

# Initial conditions
equation_of_state: 'adiabatic'  # default: 'isothermal'
initial_density: 1.0
initial_magnetic_field: 0.05  # default: 0.05 (x-direction)
acceleration_field_rms: 3.0
correlation_time: 1.0
solenoidal_weight: 1.0  # 0: fully compressive; 1: fully solenoidal

# Post-run analysis
run_analysis: True  # the list of fields is inside the bash script
