# Numeric
number_of_gpus: 1

# Mesh
number_of_cells: 128

# Hydro
equation_of_state: 'adiabatic'

# Initial conditions
initial_density: 1.0
initial_magnetic_field: 0.05  # x-direction
acceleration_field_rms: 1.0
correlation_time: 1.0
solenoidal_weight: 1.0  # 1 = fully solenoidal; 0 = fully compressive
